### ISSUE TITLE
Unable to use Azure Cloud Storage as output_uri for the ClearML Tasks

### ISSUE THREAD

**Issue by Bilal-Yousaf** [allegroai/clearml-agent#105]
Hi ClearML Team,

I am trying to use Azore Blob Storage Container as the destination storage by setting the output_uri argument in Task.init function. But I am getting error "".
I think the reason is that my blobstorage is at my own local server hosted behind proxy and I need to define DefaultEndPoint using the connection string when I use (https://pypi.org/project/azure-storage-blob/). But in the clearml.conf I can only find two configuration parameters account_name and account_key. As Clearml also uses azure-storage-blob library it should be able to handle it.

Could you please share how I can pass the connection string or the DefaultEndPoint to hit to use container?

The ClearML config:

    azure.storage {
        containers: [
            {
                account_name: "XXXXX"
                account_key: "XXXXX"
                # container_name: "clear-ml"
            }
        ]
    }

Code Block I am using:
`
task = Task.init(
        project_name='bilal',
        task_name='plotly reporting',
        output_uri='azure://goondiwindiazureblob/clear-ml'
)
`
        
        
   The ERROR I am getting is:
   
ClearML Task: overwriting (reusing) task id=64aa36d8ceae43cb808c7648f86819fc
2022-04-16 07:59:25,913 - clearml.Task - INFO - No repository found, storing script code instead
2022-04-16 08:00:55,153 - clearml.storage - ERROR - Failed uploading: <urllib3.connection.HTTPSConnection object at 0x7f169da22250>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution
2022-04-16 08:02:17,843 - clearml.storage - WARNING - Storage helper problem for .clearml.test: <urllib3.connection.HTTPSConnection object at 0x7f16bbc75850>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution
Traceback (most recent call last):
  File "/home/bilal/anaconda3/envs/infarm_clearml/lib/python3.8/site-packages/clearml/storage/helper.py", line 809, in check_write_permissions
    self.delete(path=dest_path)
  File "/home/bilal/anaconda3/envs/infarm_clearml/lib/python3.8/site-packages/clearml/storage/helper.py", line 798, in delete
    return self._driver.delete_object(self._get_object(path))
  File "/home/bilal/anaconda3/envs/infarm_clearml/lib/python3.8/site-packages/clearml/storage/helper.py", line 1921, in delete_object
    container = object.container
AttributeError: 'NoneType' object has no attribute 'container'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 9, in <module>
    task = Task.init(
  File "/home/bilal/anaconda3/envs/infarm_clearml/lib/python3.8/site-packages/clearml/task.py", line 525, in init
    task.output_uri = output_uri
  File "/home/bilal/anaconda3/envs/infarm_clearml/lib/python3.8/site-packages/clearml/task.py", line 954, in output_uri
    helper.check_write_permissions(value)
  File "/home/bilal/anaconda3/envs/infarm_clearml/lib/python3.8/site-packages/clearml/storage/helper.py", line 811, in check_write_permissions
    raise ValueError('Insufficient permissions for {}'.format(base_url))
ValueError: Insufficient permissions for azure://goondiwindiazureblob/clear-ml

**Comment by jkhenning** [comment]
Hi @Bilal-Yousaf,

I think the error you're seeing is because you did not configure `container_name` - besides the issue of proxy, why can't you set this value?

**Comment by jkhenning** [comment]
Closing here to continue the discussion in https://github.com/allegroai/clearml/issues/647
