### ISSUE TITLE
K8s Glue agent on Kubernetes fails silently

### ISSUE THREAD

**Issue by nielstenboom** [allegroai/clearml-agent#122]
Hi! 

We use the k8s glue agents on Kubernetes to enqueue experiments as pods. Occasionally we encounter that an enqueued experiment does not get picked up by the agent. I did some digging and found the following error in the logs:

```console
FATAL ERROR:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1377, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.6/ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

  File "/usr/lib/python3.6/ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 786, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1377, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.6/ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/clearml_agent/commands/worker.py", line 1560, in daemon
    gpu_queues=dynamic_gpus,
  File "/usr/local/lib/python3.6/dist-packages/clearml_agent/glue/k8s.py", line 827, in run_tasks_loop
    level="INFO",
  File "/usr/local/lib/python3.6/dist-packages/clearml_agent/commands/events.py", line 99, in send_log_events
    return self.send_events(list_events=log_events, session=session)
  File "/usr/local/lib/python3.6/dist-packages/clearml_agent/commands/events.py", line 58, in send_events
    sent_events += send_packet(lines)
  File "/usr/local/lib/python3.6/dist-packages/clearml_agent/commands/events.py", line 32, in send_packet
    'add_batch', data=jsonlines, headers={'Content-type': 'application/json-lines'}, session=session
  File "/usr/local/lib/python3.6/dist-packages/clearml_agent/commands/base.py", line 127, in post
    return session.post(service=self.service, action=endpoint, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/clearml_agent/session.py", line 300, in post
    json=json or kwargs)
  File "/usr/local/lib/python3.6/dist-packages/clearml_agent/session.py", line 308, in _manual_request
    json=json or kwargs)
  File "/usr/local/lib/python3.6/dist-packages/clearml_agent/backend_api/session/session.py", line 377, in send_request
    json=json,
  File "/usr/local/lib/python3.6/dist-packages/clearml_agent/backend_api/session/session.py", line 305, in _send_request
    method, url, headers=headers, auth=auth, data=data, json=json, timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

It seems that something went wrong in the connection when posting the experiment (?). This leads to our experiment not being scheduled at all (seems the k8s glue scheduler gets sort of stuck after encountering this error. I did a restart of the agent and it worked immediately.

## Proposed fix

It would be great if the clearml-agent is actually allowed to crash when it encounters an exception. When running on Kubernetes it will make sure the pod is restarted.

Maybe we could add a new config option that could be checked if the exception here:

https://github.com/allegroai/clearml-agent/blob/26e62da1a8fb4b66361a5d6a4d852d50b1e0a158/clearml_agent/commands/worker.py#L1553

This check then differentiates if the exception should be propogated or caught. What do you guys think?

**Comment by jkhenning** [comment]
@nielstenboom sounds good, care to suggest a PR? 🙂

**Comment by nielstenboom** [comment]
For sure! I'll have a crack at it tomorrow

**Comment by nielstenboom** [comment]
Let me know what you think of this PR @jkhenning!

https://github.com/allegroai/clearml-agent/pull/123
