### ISSUE TITLE
clearml-agent crashes if CLEARML_API_DEFAULT_REQ_METHOD variable is set

### ISSUE THREAD

**Issue by ruk0sh** [allegroai/clearml-agent#125]
I have corporate proxy which cuts GET requests with payload, so must use `CLEARML_API_DEFAULT_REQ_METHOD` to override default settings and allow API calls pass through.
`clearml-data` works fine.
But it turns out this overriding mechanism was not implemented in `clearml-agent`.
```bash
>>>$ export CLEARML_API_DEFAULT_REQ_METHOD=POST
>>>$ clearml-agent --debug daemon --queue default  --foreground
```
```
Traceback (most recent call last):
  File "/usr/local/bin/clearml-agent", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/clearml_agent/__main__.py", line 83, in main
    return run_command(parser, args, command_name)
  File "/usr/local/lib/python3.6/dist-packages/clearml_agent/__main__.py", line 42, in run_command
    command = command_class(**vars(args))
  File "/usr/local/lib/python3.6/dist-packages/clearml_agent/helper/base.py", line 241, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/clearml_agent/commands/worker.py", line 620, in __init__
    super(Worker, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/clearml_agent/commands/base.py", line 98, in __init__
    self._session = self._get_session(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/clearml_agent/commands/base.py", line 113, in _get_session
    return Session(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/clearml_agent/session.py", line 94, in __init__
    super(Session, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/clearml_agent/backend_api/session/session.py", line 116, in __init__
    self.config["api.http.default_method"] = ENV_API_DEFAULT_REQ_METHOD.get()
TypeError: 'Config' object does not support item assignment
```

The [Config class](https://github.com/allegroai/clearml-agent/blob/master/clearml_agent/backend_config/config.py) just does not contain `__setitem__` method.

**Comment by qwaxys** [comment]
@ruk0sh this has been solved in v1.5.0rc0
https://github.com/allegroai/clearml-agent/releases/tag/v1.5.0rc0

Can you give that a try and see if that works for you?

**Comment by jkhenning** [comment]
@ruk0sh I think you need to use v1.5.0rc1... 🙂

**Comment by qwaxys** [comment]
@ruk0sh my bad, you're indeed looking for  v1.5.0rc1
You can find it here: https://pypi.org/project/clearml-agent/1.5.0rc1/

**Comment by ruk0sh** [comment]
> @ruk0sh my bad, you're indeed looking for v1.5.0rc1 You can find it here: https://pypi.org/project/clearml-agent/1.5.0rc1/

This helped. Thank you! 🚀
